---
title: "STAT 201 Peer Review Instructions"
output: github_document
---


For this peer review, you will be **individually** providing feedback to another group's proposal. You will be sent an email with the proposal to review.

We deliberately set up the review so that each member of your group is assigned to review a _different_ group's proposal. This allows your group to collectively see a larger variety of proposals.

## Instructions

Bundle all of your feedback into a single document of your choice, and submit that to canvas. There is no page limit. The teaching team will deliver the feedback to your reviewee. 

Your review should contain the following elements:

- As you read through the proposal, point out anything that you think is confusing, or is not communicated effectively. When possible, provide suggestions for improvement. If everything looks good to you, say why it looks good.
- What part of the proposal is the most effective, and why?
- What part of the proposal is the least effective, and why? Provide a suggestion for improvement. 
- Provide feedback on English, spelling, and grammar (if applicable).

The rubric can be found on canvas. In short, "mechanics" (10%) evaluates the composition of your submission, "reasoning" (70%) evaluates your feedback, and "writing" (20%) evaluates your English, spelling, and grammar.

## Submission

Please submit your work to canvas. 
