name: stat_301
channels:
 - conda-forge
 - r 
 - nodefaults
dependencies:
  - anyio
  - jupyterlab
  - jupyterlab-git
  - jupyter-resource-usage
  - jupyterlab_rise
  - jupytext
  - nbgitpuller
  - python=3.11
  - r-aer 
  - r-base 
  - r-binom 
  - r-boot 
  - r-car 
  - r-cardata 
  - r-caret 
  - r-caret 
  - r-cowplot 
  - r-crayon 
  - r-devtools 
  - r-e1071 
  - r-faraway 
  - r-forecast 
  - r-ggally 
  - r-glmbb
  - r-glmnet 
  - r-gridextra 
  - r-gridgraphics 
  - r-gsdesign 
  - r-hexbin 
  - r-htmltools 
  - r-htmlwidgets 
  - r-infer 
  - r-irkernel 
  - r-islr
  - r-islr2
  - r-janitor 
  - r-kknn 
  - r-latex2exp 
  - r-leaps 
  - r-memoise
  - r-mlbench 
  - r-mltools 
  - r-nycflights13 
  - r-palmerpenguins
  - r-performance 
  - r-qqplotr 
  - r-randomforest 
  - r-rcurl 
  - r-rmarkdown 
  - r-rodbc 
  - r-rpostgres 
  - r-rsqlite 
  - r-see 
  - r-shiny 
  - r-stringi=1.7.12
  - r-testthat 
  - r-tidymodels 
  - r-tidyverse 
  - r-titanic 
  - unixodbc
